In [ ]:
import numpy as np

print(np.zeros(10,dtype=int))
print(np.ones(10,dtype=int))
print(np.ones(10,dtype=int)*5)

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[5 5 5 5 5 5 5 5 5 5]


Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a
given array

In [ ]:
arr=np.arange(1,11).reshape(2,5)

print(arr)

print ("total sum of array",np.sum(arr))

print ("sum of each colums of array",np.sum(arr,axis=0))

print ("sum of each row of array",np.sum(arr,axis=1))




[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
total sum of array 55
sum of each colums of array [ 7  9 11 13 15]
sum of each row of array [15 40]


Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [ ]:
arr=np.arange(1,26).reshape(5,5)


print("array is \n",arr)
print("after adding value to each eliment \n",np.add(arr,2))
print("after substracting value to each eliment \n",np.subtract(arr,1))
print("after divideing value to each eliment \n",np.divide(arr,5))
print("after multiplying value to each eliment \n",np.multiply(arr,5))

print(np.multiply(arr,5))

array is 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
after adding value to each eliment 
 [[ 3  4  5  6  7]
 [ 8  9 10 11 12]
 [13 14 15 16 17]
 [18 19 20 21 22]
 [23 24 25 26 27]]
after substracting value to each eliment 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
after divideing value to each eliment 
 [[0.2 0.4 0.6 0.8 1. ]
 [1.2 1.4 1.6 1.8 2. ]
 [2.2 2.4 2.6 2.8 3. ]
 [3.2 3.4 3.6 3.8 4. ]
 [4.2 4.4 4.6 4.8 5. ]]
after multiplying value to each eliment 
 [[  5  10  15  20  25]
 [ 30  35  40  45  50]
 [ 55  60  65  70  75]
 [ 80  85  90  95 100]
 [105 110 115 120 125]]
[[  5  10  15  20  25]
 [ 30  35  40  45  50]
 [ 55  60  65  70  75]
 [ 80  85  90  95 100]
 [105 110 115 120 125]]


Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in
degree.

In [ ]:
arr=np.arange(10)
print("array \n",arr)
print("sin \n",np.sin(arr*np.pi/180))
print("cos \n",np.cos(arr*np.pi/180))
print("tan \n",np.tan(arr*np.pi/180))


array 
 [0 1 2 3 4 5 6 7 8 9]
sin 
 [0.         0.01745241 0.0348995  0.05233596 0.06975647 0.08715574
 0.10452846 0.12186934 0.1391731  0.15643447]
cos 
 [1.         0.9998477  0.99939083 0.99862953 0.99756405 0.9961947
 0.9945219  0.99254615 0.99026807 0.98768834]
tan 
 [0.         0.01745506 0.03492077 0.05240778 0.06992681 0.08748866
 0.10510424 0.12278456 0.14054083 0.15838444]


Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the
index labels

In [12]:
import pandas as pd
dic={"elm1":1,"elm2":2,"elm3":3,"elm4":4,"elm5":5,"elm6":6}
df=pd.DataFrame(dic.items())
df

0  1
0  elm1  1
1  elm2  2
2  elm3  3
3  elm4  4
4  elm5  5
5  elm6  6

Write a Pandas program to join the two given dataframes along rows and assign all data.

In [39]:
dic1={'Name':['A', 'B', 'C', 'D'],'Age':[28,34,29,42]}
dic2={'address':['Bengaluru', 'Chennai', 'Pune', 'Mumbai'],'pincode':[123,456,789,456]}
datafrm_1=pd.DataFrame(dic1)
datafrm_2=pd.DataFrame(dic2)
print(pd.concat([datafrm_1, datafrm_2], axis=1))

df=pd.concat([datafrm_1, datafrm_2], axis=0)
df2=df.copy()
df.fillna("Not Available")



  Name  Age    address  pincode
0    A   28  Bengaluru      123
1    B   34    Chennai      456
2    C   29       Pune      789
3    D   42     Mumbai      456


Name            Age        address        pincode
0              A             28  Not Available  Not Available
1              B             34  Not Available  Not Available
2              C             29  Not Available  Not Available
3              D             42  Not Available  Not Available
0  Not Available  Not Available      Bengaluru            123
1  Not Available  Not Available        Chennai            456
2  Not Available  Not Available           Pune            789
3  Not Available  Not Available         Mumbai            456

Write a Pandas program to detect missing values of a given DataFrame. Display True or False.

*   List item
*   List item



In [29]:
df.isna()

Name    Age  address  pincode
0  False  False     True     True
1  False  False     True     True
2  False  False     True     True
3  False  False     True     True
0   True   True    False    False
1   True   True    False    False
2   True   True    False    False
3   True   True    False    False

Write a Pandas program to create and display a one-dimensional array-like object containing an array of
data.

In [34]:
pd.Series([1,2,3,4,5,6,7,8,9])


0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64